# Generated by Django 4.2.3 on 2023-08-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0003_alter_chef_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='short_info',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
