# Generated by Django 4.2.3 on 2023-08-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0004_chef_short_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
