# Generated by Django 4.2.3 on 2023-08-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0007_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='content',
            new_name='message',
        ),
    ]
