# Generated by Django 4.2.3 on 2023-08-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0008_rename_content_chatmessage_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chef',
            options={'verbose_name': 'Chef', 'verbose_name_plural': 'Chefs'},
        ),
    ]
