# Generated by Django 4.2.3 on 2023-08-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0009_alter_chef_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
