# Generated by Django 4.2.3 on 2023-07-31 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='host',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='name',
            new_name='title',
        ),
    ]
