# Generated by Django 4.2.3 on 2023-07-31 13:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_rename_host_community_admin_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='CommunityChat',
        ),
    ]
