# Generated by Django 4.2.3 on 2023-07-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_rename_message_communitychat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='title',
            new_name='name',
        ),
    ]
