# Generated by Django 4.2.3 on 2023-07-31 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_rename_title_community_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='name',
            new_name='title',
        ),
    ]
