# Generated by Django 4.2.3 on 2023-07-31 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_rename_name_community_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='title',
            new_name='name',
        ),
    ]
