# Generated by Django 4.2.3 on 2023-08-01 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_chatroom_message_delete_communitychat'),
    ]

    operations = [
        migrations.CreateModel(
            name='communitieschat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.topic')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='participants',
            new_name='users',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
