# Generated by Django 4.2.3 on 2023-08-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_communitieschat_remove_message_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='topic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
