# Generated by Django 4.2.3 on 2023-08-02 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0009_alter_community_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitieschat',
            name='room',
        ),
        migrations.AddField(
            model_name='communitieschat',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.community'),
        ),
        migrations.AlterField(
            model_name='communitieschat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
